
# Site settings
title: Nitish Patel
email: patel.nitish22@gmail.com
description: "Fullstack JavaScript Developer (React.js, Node.js, Cloud & AI Systems)"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: #username
github_username:  nitishpatel26
time: "2026-07-05"

# Build settings
markdown: kramdown

#
####################################
# Site Owner configuration
####################################
#
owner:
  name: Nitish Patel
  avatar: Nitish.jpg
  job: "<a href=\"https://www.ibm.com/in-en/\" target=\"_blank\">@IBM</a>"
  bio: # "<b>14 years</b> of experience in software development integration of web based application.

# Excellent knowledge and experience of Nodejs, Reactjs (Classes, Hooks), Typescript, Redux, Saga, Redux-Form, Hapijs, Swagger, Sequelizejs, ReactStrap, semantic-ui, Material-ui, Ant Designs, AngularJs, Mysql/Postgresql/Mssql/MongoDb"
  email: patel.nitish22@gmail.com
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nitishpatel26
  stackoverflow: #username
  linkedin: nitish-patel
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  medium: #username
  flickr: #username
  codepen: #username
  pdfFormat: Monty_Resume_062026.pdf